export const customersData = [
  // {
  //   id: 11110,
  //   name: 'Customer Name',
  //   company: 'Company',
  //   phone: 'Phone Number',
  //   email: 'Email',
  //   country: 'Country',
  //   status: 'Status',
  // },
  {
    id: 11111,
    nameUser: 'Jane Cooper',
    company: 'Microsoft',
    phone: '(225) 555-0118',
    email: 'jane@microsoft.com',
    country: 'United States',
    isStatus: 'Active',
  },
  {
    id: 22222,
    nameUser: 'Floyd Miles',
    company: 'Yahoo',
    phone: '(205) 555-0100',
    email: 'floyd@yahoo.com',
    country: 'Kiribati',
    isStatus: 'Inactive',
  },
  {
    id: 33333,
    nameUser: 'Ronald Richards',
    company: 'Adobe',
    phone: '(302) 555-0107',
    email: 'ronald@adobe.com',
    country: 'Israel',
    isStatus: 'Inactive',
  },
  {
    id: 44444,
    nameUser: 'Marvin McKinney',
    company: 'Tesla',
    phone: '(252) 555-0126',
    email: 'marvin@tesla.com',
    country: 'Iran',
    isStatus: 'Active',
  },
  {
    id: 55555,
    nameUser: 'Jerome Bell',
    company: 'Google',
    phone: '(629) 555-0129',
    email: 'jerome@google.com',
    country: 'Réunion',
    isStatus: 'Active',
  },
  {
    id: 66666,
    nameUser: 'Kathryn Murphy',
    company: 'Microsoft',
    phone: '(406) 555-0120',
    email: 'kathryn@microsoft.com',
    country: 'Curaçao',
    isStatus: 'Active',
  },
  {
    id: 77777,
    nameUser: 'Jacob Jones',
    company: 'Yahoo',
    phone: '(208) 555-0112',
    email: 'jacob@yahoo.com',
    country: 'Brazil',
    isStatus: 'Active',
  },
  {
    id: 88888,
    nameUser: 'Kristin Watson',
    company: 'Facebook',
    phone: '(704) 555-0127',
    email: 'kristin@facebook.com',
    country: 'Åland Islands',
    isStatus: 'Inactive',
  },
];
